# Generated by Django 5.0.6 on 2025-11-14 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SimulationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('simulation_id', models.CharField(max_length=64, unique=True)),
                ('message', models.TextField()),
                ('idf_file', models.CharField(blank=True, max_length=255)),
                ('used_mock_data', models.BooleanField(default=False)),
                ('total_energy', models.FloatField()),
                ('energy_by_type', models.JSONField()),
                ('energy_breakdown', models.JSONField()),
                ('additional_info', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
